# Generated by Django 5.0 on 2023-12-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=350)),
                ('url_thumb', models.URLField(blank=True, null=True)),
                ('url_episodio', models.URLField(blank=True, null=True)),
                ('incorporar_player', models.TextField(blank=True, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios_anime', to='animes.anime')),
            ],
        ),
    ]
