# Generated by Django 5.0 on 2023-12-12 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='postado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
