# Generated by Django 5.0 on 2023-12-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0010_anime_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
