# Generated by Django 5.0 on 2023-12-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0011_episodio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodios',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
