# Generated by Django 5.0 on 2023-12-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0012_alter_anime_episodios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
