# Generated by Django 5.0 on 2023-12-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0013_alter_episodio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='duracao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
