# Generated by Django 5.0 on 2023-12-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0014_anime_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
    ]
