# Generated by Django 5.0 on 2023-12-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0016_anime_vizualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='vizualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
