# Generated by Django 5.0 on 2023-12-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0018_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
